using System;
using System.Collections.Generic;

namespace StorageI.Models
{
    public partial class Bpivot
    {
        public string? Псг { get; set; }
        public string? Пч { get; set; }
        public string? Category { get; set; }
        public decimal? AcBr { get; set; }
        public decimal? AcRezerv { get; set; }
        public decimal? AcRemont { get; set; }
        public decimal? AclBr { get; set; }
        public decimal? AclRezerv { get; set; }
        public decimal? AclRemont { get; set; }
        public decimal? АнрBr { get; set; }
        public decimal? АнрRezerv { get; set; }
        public decimal? АнрRemont { get; set; }
        public decimal? АсаBr { get; set; }
        public decimal? АсаRezerv { get; set; }
        public decimal? АсаRemont { get; set; }
        public decimal? АсоBr { get; set; }
        public decimal? АсоRezerv { get; set; }
        public decimal? АсоRemont { get; set; }
        public decimal? АвBr { get; set; }
        public decimal? АвRezerv { get; set; }
        public decimal? АвRemont { get; set; }
        public decimal? АсаАппАсмBr { get; set; }
        public decimal? АсаАппАсмRezerv { get; set; }
        public decimal? АсаАппАсмRemont { get; set; }
        public decimal? ПнсBr { get; set; }
        public decimal? ПнсRezerv { get; set; }
        public decimal? ПнсRemont { get; set; }
        public decimal? AlBr { get; set; }
        public decimal? AlRezerv { get; set; }
        public decimal? AlRemont { get; set; }
        public decimal? КпBr { get; set; }
        public decimal? КпRezerv { get; set; }
        public decimal? КпRemont { get; set; }
        public decimal? АрBr { get; set; }
        public decimal? АрRezerv { get; set; }
        public decimal? АрRemont { get; set; }
        public decimal? АсмпПсаBr { get; set; }
        public decimal? АсмпПсаRezerv { get; set; }
        public decimal? АсмпПсаRemont { get; set; }
        public decimal? АшBr { get; set; }
        public decimal? АшRezerv { get; set; }
        public decimal? АшRemont { get; set; }
        public decimal? УксАбгBr { get; set; }
        public decimal? УксАбгRezerv { get; set; }
        public decimal? УксАбгRemont { get; set; }
        public decimal? ПожПоездКорабльBr { get; set; }
        public decimal? ПожПоездКорабльRezerv { get; set; }
        public decimal? ПожПоездКорабльRemont { get; set; }
        public decimal? Tofirst { get; set; }
        public decimal? Totow { get; set; }
        public decimal? АсмрхBr { get; set; }
        public decimal? АсмрхRezerv { get; set; }
        public decimal? АвсBr { get; set; }
        public decimal? АвсRezerv { get; set; }
        public decimal? РемонтОсновной { get; set; }
        public decimal? РемонтСпециальной { get; set; }
        public decimal? ПожарныйКорабльРемонт { get; set; }
        public decimal? ПлавСредства { get; set; }
        public decimal? Болотоходы { get; set; }
        public decimal? Мотопомпы { get; set; }
        public decimal? Прочее { get; set; }
        public decimal? SizodBr { get; set; }
        public decimal? SizodRezerv { get; set; }
        public decimal? КостюмыЛ1Таск { get; set; }
        public decimal? КостюмыТок { get; set; }
        public decimal? КостюмыДругие { get; set; }
        public decimal? ГасиРасчёт { get; set; }
        public decimal? ГасиРезерв { get; set; }
        public decimal? ПоСписку { get; set; }
        public decimal? Налицо { get; set; }
        public decimal? Всего { get; set; }
        public decimal? Резерв { get; set; }
        public decimal? Нк { get; set; }
        public decimal? Диспетчер { get; set; }
        public decimal? Пнк { get; set; }
        public decimal? Ко { get; set; }
        public decimal? Водитель { get; set; }
        public decimal? Пожарный { get; set; }
        public decimal? Гдзс { get; set; }
        public decimal? ВсегоОтс { get; set; }
        public decimal? Отпуск { get; set; }
        public decimal? ПоБольничному { get; set; }
        public decimal? Командировка { get; set; }
        public decimal? Некомплект { get; set; }
        public decimal? ПрочиеОтс { get; set; }
        public decimal? ПенаРасчёт { get; set; }
        public int ПорошокРасчёт { get; set; }
        public decimal? ПенаРезерв { get; set; }
        public int ПорошокРезерв { get; set; }
        public decimal? Дт { get; set; }
        public decimal? Бензин { get; set; }
        public string? Начкар { get; set; }
        public int? Id { get; set; }
        public int? Parent { get; set; }
        public int Norder { get; set; }
        public int Isitog { get; set; }
    }
}
